### ISSUE TITLE
Links to documentation are incorrect

### ISSUE THREAD

**Issue by guusdk** [stuartgunter/couchbase-maven-plugin#1]
In the README file, the link that points to the plugin documentation is pointing to a page that shows a 404 error. Can the documentation be made available again please?

**Comment by stuartgunter** [comment]
Thanks for pointing that out. Not sure why it isn't working anymore. Seems GitHub isn't picking it up as expected.

I'll investigate.

**Comment by stuartgunter** [comment]
After some investigation, it seems this is a problem with GitHub and not with this repo. I've contacted them to ask for some investigation to be done on their side and will hopefully have good news soon.

Thanks for pointing out the problem!

**Comment by stuartgunter** [comment]
GitHub have kindly fixed this, so docs are back up & running.

**Comment by guusdk** [comment]
I've verified that the links are working now. Thanks for the quick response!
